package com.openjiuwen.auto_harness.schema;

/**
 * Structured PR draft generated by the communicate agent.
 *
 * <p>Mirrors Python's {@code PullRequestDraft} in
 * {@code openjiuwen.auto_harness.schema}.</p>
 */
public class PullRequestDraft {
    private String title = "";
    private String body = "";
    private String kind = "";

    public PullRequestDraft() {
    }

    public PullRequestDraft(String title, String body, String kind) {
        setTitle(title);
        setBody(body);
        setKind(kind);
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title != null ? title : "";
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body != null ? body : "";
    }

    public String getKind() {
        return kind;
    }

    public void setKind(String kind) {
        this.kind = kind != null ? kind : "";
    }
}
